Holodeck/Environments.py
Holodeck/Holodeck.py
Holodeck/Shmem.py
Holodeck/ShmemClient.py
example.py

Companion PR of https://github.com/BYU-PCCL/Holodeck/pull/25

Command line args

---

Holodeck/Agents.py
Holodeck/Environments.py
Holodeck/Holodeck.py
Holodeck/Sensors.py
Holodeck/Shmem.py
Holodeck/ShmemClient.py
Holodeck/__init__.py
README.md
example.py
install.py

This PR contains a lot of changes to make Holodeck much more usable. It includes:
* An updated README
* An additional semaphore which allows Python to wait for the world to load
* Improved installation with automatic downloading of the worlds
It also
* Removed the TQDM dependency
* Removed Python 2 compatible code
* Fixed a number of minor bugs

Wait for binary

---

Holodeck/Environments.py
Holodeck/Holodeck.py
example.py

Updated Environments to allow for multi agent systems.

Multiagent

---

Holodeck/Sensors.py

Maybe we should find a better way to add new sensors, it could get out of hand if we have to edit them often. I incremented to 12 because RotationSensor is supposed to be 11.

Collision sensor

---

Holodeck/Command.py
Holodeck/Environments.py
Holodeck/Shmem.py
Holodeck/command.py

Created a class hierarchy to handle the commands, and to make sure they are formatted correctly. Opened up the command buffer to communicate with the Holodeck. Included a function in HolodeckEnvironemnt that is used to spawn new agents. Give it the agent name, type, and location to spawn. It will send the message to the Holodeck to spawn the agent, and open up the correct memory mapped buffers to communicate with it by name.

Command center

---

install.py

The tilde is now replaced properly on both windows and linux

Home directory

---

Holodeck/Agents.py
Holodeck/Environments.py
Holodeck/Sensors.py

Added ability to get android index based on name. Updated android vector length.

Android Update

---

example.py

The changes in editor_example() will make life easier for when I do testing, not sure if it's the same for everyone else?

Update examples to include new features

---

holodeck/sensors.py

Updated sensors

---

example.py
holodeck/agents.py
holodeck/command.py
holodeck/environments.py
holodeck/holodeckclient.py
holodeck/hyperparameters.py
holodeck/shmem.py

Simplified HolodeckClient. Fixed info function. Added control schemes

---

holodeck/packagemanager.py

Should fix the occasional unicode encoding error by simply catching it and printing an alternative progress notification.

Unicode fix

---

holodeck/command.py
holodeck/environments.py

Added Settings Commands:
- Can set weather to rain or cloudy
- Can set day time
- Can start a day-night cycle
- Can set fog density

Settings commands

---

holodeck/agents.py
holodeck/environments.py
setup.py

Please check you are happy with the names of the enums. I'm not sure I'm happy with them, but it's the best I could come up with.
I also added a convenience function to the environment.
Issue #89

Added control scheme enums, updated pip info

---

example.py
holodeck/command.py
holodeck/environments.py

Added the Teleport camera command

Teleport camera

---

holodeck/command.py
holodeck/environments.py

Adds the ability to draw debug points, lines, arrows and boxes into the world.

Draw debug

---

holodeck/shmem.py

Previously there was a race condition where after `os.ftruncate()`
the size of the new file wouldn't be updated by the time `mmap.mmap()`
was called. An fsync seems to be the solution[1].
Also resolved an issue where open files were not closed. Not all of the
file leaks have been resolved, there is a TODO describing the problem better.
[1] https://lwn.net/Articles/457667/ see "When Should You Fsync?"

Fix #115 mmap length greater than file size

---

.gitignore
holodeck/agents.py
holodeck/command.py
holodeck/environments.py
holodeck/sensors.py

This adds the add and remove sensor commands as well as adds methods that implement those commands to the holodeck agent. Sensors and agents are also given sensor_type and agent_type members respectively to facilitate sending of these new commands. Consequently, some changes are made to sensor and agent definitions and factories.

Dynamic sensors

---

holodeck/agents.py
holodeck/command.py
holodeck/environments.py
holodeck/sensors.py

Task Fixes

---

holodeck/tests/test_utils.py
holodeck/tests/unitscoord_pytest.py

Updated some of the units testing so it is working properly.

fixed tests

---

holodeck/sensors.py

Adds the location task to holodeck.

Init location task

---

holodeck/environments.py

Use correct dictionary

---

holodeck/packagemanager.py

Fix #105, add warning message to FileNotFound error

---

holodeck/packagemanager.py
holodeck/util.py

Also alerts the user when they have stale packages

Change package URL, add .prune() method

---

holodeck/packagemanager.py

Any further bugs are @MaxRobinsonTheGreat 's fault

Fix path not found error

---

holodeck/agents.py
holodeck/command.py
holodeck/environments.py
holodeck/exceptions.py
holodeck/holodeck.py
holodeck/holodeckclient.py
holodeck/packagemanager.py
holodeck/pylintrc
holodeck/sensors.py
holodeck/spaces.py
holodeck/tests/test_utils.py
holodeck/util.py

See https://github.com/BYU-PCCL/holodeck/wiki/Linting-How-To

Linting (#242)

---

example-world-attacher.py
holodeck/agents.py
holodeck/command.py
holodeck/environments.py

Plumb rotation to engine side

---

docs/changelog/changelog.rst
docs/make.bat
docs/usage/hotkeys.rst
tests/README.md

- Add some missing entries to the changelog
- Add note about shift moving you faster
- Add instructions for running tests
- Add batch file to build docs on Windows

Changelog & doc updates

---

src/holodeck/agents.py

I built remorse into the nav agent to discourage it from destroying humans

Removed unit conversion on python side

---

docs/changelog/changelog.rst
src/holodeck/packagemanager.py

Allow download from URL

---

README.md
docs/_static/themes_override.css
docs/changelog/changelog.rst
docs/conf.py
docs/usage/hotkeys.rst
docs/usage/running-headless.rst
docs/usage/usage.rst

Fix tables that are too wide as well
#253

Add docs for HUD

---

docs/changelog/changelog.rst
src/holodeck/agents.py
src/holodeck/command.py
src/holodeck/environments.py

Agent follower will now default to following the main agent, rather than whatever agent is found first

Follow main agent

---

docs/packages/Dexterity/Playroom/Playroom-StandFromGround.rst
docs/packages/Dexterity/Playroom/Playroom-StandFromStanding.rst

Added docs for advanced android scenarios

---

src/holodeck/agents.py
src/holodeck/environments.py
src/holodeck/joint_constraints.py
tests/agents/androidagent/test_androidagent_joint_constraints.py
tests/agents/handagent/test_handagent_joint_constraints.py

Got the joints constraints values from the game for the Android and Hand agents and saved them statically as a dictionary. Also added methods to retrieve the constraints (swing1Limit, swing2Limit, and twistLimit)

Joint constraints/bounds (issue #335)

---

docs/packages/docs/scenarios.rst
src/holodeck/environments.py
tests/agents/test_randomization.py

Added optional randomization to agents' start location. This fixes #295

Agent start location randomization #295

---

example.py

We hadn't updated them for the scenario config changes.

Fix Editor examples (#358)

---

docs/changelog/changelog.rst
src/holodeck/holodeckclient.py

This should address the error when starting the engine up

Increase timeout

---

docs/changelog/changelog.rst
docs/packages/docs/tasks/distance-task.rst

May want to wait until test is made to merge

Added documentation for the 3ddistance flag

---

docs/changelog/changelog.rst
src/holodeck/environments.py

- documentation for #361 bug fix
- the make method now sends the `is_main_agent` flag when adding an agent

Editor crash fix doc

---

docs/usage/getting-started.rst

Update "getting started" doc to reflect new sensor API structure. Fixes #352.

Update "getting started" doc to fix #352

---

tests/worlds/mazeworld/conftest.py

Correctly skip MazeWorld tests (#381)

---

README.md
docs/usage/examples/multi-agent.rst
example.py

* Updates README documentation to stop using old `Sensors` interface
* Changes `multi_agent_example` to use correct name for scenario: `CyberPunkCity-Follow`
* Adds some variables to `multi_agent_example` loop to make it more similar to documentation example

Update sensor data examples in documentation and README

---

docs/changelog/changelog.rst
src/holodeck/environments.py
tests/scenarios/test_prop_spawning.py

Spawn actor

---

src/holodeck/environments.py

We were not handling SIGHUB previously so resources were not freed up when the terminal was killed/closed. This commit fixes those issues.
Closes #414

Install a handler for SIGHUB

---

src/holodeck/environments.py
tests/scenarios/test_prop_spawning.py

Prop spawning

---

src/holodeck/environments.py

Fix event handling error on Windows

---

src/holodeck/command.py

I forget what we were waiting for, but I fixed the problem where it shows up and other places where it could show up. Also I think everything else that I work on will be tied to this branch so I think I want to pull now

Numpy array fix
